[[redirects]]
  from = "/"
  to = "https://readingcorner-fahsd3m7.b4a.run/api"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"